### ISSUE TITLE
How/where to save these forms?

### ISSUE THREAD

**Issue by bwyborney** [bwyborney/rq-checkin#1]
Let's avoid saving these to an external server. They are going to contain internal information.
So, we can either save the files to our local computers, or encode them into each ticket in RQ, using a note or custom form.
It's not obvious to me how we can programmatically add notes or custom forms, but if we could - problem solved.

**Comment by vaeleborn** [comment]
Yeah, if we can find the API call to add a note I'd say that mixed with making that note hidden would be the best route. Regardless it may be a good idea to encrypt the data  first anyway so someone couldn't listen on calls and pull the packets

**Comment by vaeleborne** [comment]
Side note, will be using this account not my old one.

**Comment by cprEugeneBen** [comment]
Idea! We can make a custom form which is required for every new repair ticket. It contains a link/button to pull up the form. Since we'll already have the editing window for that custom form open, the program can just auto-save it with the data.
